// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqyk4qTBT9dt44jj7PfCHn-6khFqrNOlM',
    appId: '1:658213499415:web:4c0bc876d3b6927209e252',
    messagingSenderId: '658213499415',
    projectId: 'chatapp-f4148',
    authDomain: 'chatapp-f4148.firebaseapp.com',
    storageBucket: 'chatapp-f4148.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhUbGFL_Lxus_TmlrwO6hMLsm_X4EZiyw',
    appId: '1:658213499415:android:ca42ca6a8d96b43909e252',
    messagingSenderId: '658213499415',
    projectId: 'chatapp-f4148',
    storageBucket: 'chatapp-f4148.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqBtuek2Ns_a0pRGPdjPN_pI06UjTlZcw',
    appId: '1:658213499415:ios:29e6c43fdfcee6c209e252',
    messagingSenderId: '658213499415',
    projectId: 'chatapp-f4148',
    storageBucket: 'chatapp-f4148.appspot.com',
    iosClientId: '658213499415-d9ls1fqr26bncrqi0qeh7s28s0das152.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqBtuek2Ns_a0pRGPdjPN_pI06UjTlZcw',
    appId: '1:658213499415:ios:d72023c402b9e7b309e252',
    messagingSenderId: '658213499415',
    projectId: 'chatapp-f4148',
    storageBucket: 'chatapp-f4148.appspot.com',
    iosClientId: '658213499415-uj9527k8ov063e7m1nuvun8ged64sb2j.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
